"""Book Table

Revision ID: cdd05cc643ea
Revises: d9427f46ce94
Create Date: 2023-01-20 11:49:57.906283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd05cc643ea'
down_revision = 'd9427f46ce94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
